---
# tasks file for sysdig (Ubuntu specific)

- name: Download Draios GPG key
  apt_key: >
    url=https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public
    state=present
  tags: sysdig

- name: Configure Draios APT repository
  apt_repository: >
    repo='deb http://download.draios.com/stable/deb stable-$(ARCH)/'
    state=present
  tags: sysdig

- name: Install sysdig packages
  apt: >
    name={{ item }}
    state=present
    force=yes
    update_cache=yes
  with_items: sysdig_packages
  tags: sysdig
